// Regenerates data.js from a Spotify playlist CSV export (e.g. from Exportify).
// Usage: node scripts/prep.mjs "path/to/export.csv"
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const csvPath = process.argv[2];
if (!csvPath) { console.error('Usage: node scripts/prep.mjs <playlist.csv>'); process.exit(1); }
const raw = readFileSync(csvPath, 'utf8');

function parseCSV(text) {
  const rows = [];
  let row = [], field = '', inQ = false;
  for (let i = 0; i < text.length; i++) {
    const c = text[i];
    if (inQ) {
      if (c === '"') {
        if (text[i + 1] === '"') { field += '"'; i++; }
        else inQ = false;
      } else field += c;
    } else {
      if (c === '"') inQ = true;
      else if (c === ',') { row.push(field); field = ''; }
      else if (c === '\n') { row.push(field); rows.push(row); row = []; field = ''; }
      else if (c !== '\r') field += c;
    }
  }
  if (field || row.length) { row.push(field); rows.push(row); }
  return rows;
}

const rows = parseCSV(raw);
const header = rows[0];
const idx = Object.fromEntries(header.map((h, i) => [h, i]));

const adders = [];
const tracks = [];
for (const r of rows.slice(1)) {
  if (r.length < header.length) continue;
  const get = (name) => r[idx[name]];
  const addedBy = get('Added By');
  let bi = adders.indexOf(addedBy);
  if (bi === -1) { adders.push(addedBy); bi = adders.length - 1; }
  const rel = get('Release Date') || '';
  const year = parseInt(rel.slice(0, 4)) || null;
  const num = (name) => { const v = parseFloat(get(name)); return isNaN(v) ? null : v; };
  tracks.push({
    n: get('Track Name'),
    ar: get('Artist Name(s)'),
    al: get('Album Name'),
    y: year,
    d: Math.round((num('Duration (ms)') || 0) / 1000),
    p: num('Popularity') ?? 0,
    x: get('Explicit') === 'true' ? 1 : 0,
    b: bi,
    a: (get('Added At') || '').slice(0, 10),
    g: (get('Genres') || '').split(',').map(s => s.trim()).filter(Boolean),
    da: num('Danceability'),
    en: num('Energy'),
    va: num('Valence'),
    ac: num('Acousticness'),
    ins: num('Instrumentalness'),
    te: num('Tempo'),
    lo: num('Loudness'),
  });
}

const outPath = join(dirname(fileURLToPath(import.meta.url)), '..', 'data.js');
const out = `// Generated by scripts/prep.mjs — do not edit by hand.\nconst ADDERS = ${JSON.stringify(adders)};\nconst TRACKS = ${JSON.stringify(tracks)};\n`;
writeFileSync(outPath, out);
console.log(`Wrote data.js: ${tracks.length} tracks, adders: ${adders.join(', ')}`);
